# -*- coding: utf-8 -*-
"""Copia de RNA_Intro_2026_MIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LN0IW4CqQcVJaXzqp72lm1siFpzRDkc_

# Introducción a Redes Neuronales
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import pylab as pl
from matplotlib import pyplot as plt

# Función para visualizar un conjunto de datos en 2D
def plot_data(X, y, size=None):
    y_unique = np.unique(y)
    colors = pl.cm.rainbow(np.linspace(0.0, 1.0, y_unique.size))
    for this_y, color in zip(y_unique, colors):
        this_X = X[y == this_y]
        pl.scatter(this_X[:, 0], this_X[:, 1],  c=color,
                    alpha=0.5, edgecolor='k', s=size,
                    label="Class %s" % this_y)
    pl.legend(loc="best")
    pl.title("Data")

# Función para visualizar de la superficie de decisión de un clasificador
def plot_decision_region(X, pred_fun):
    min_x = np.min(X[:, 0])
    max_x = np.max(X[:, 0])
    min_y = np.min(X[:, 1])
    max_y = np.max(X[:, 1])
    min_x = min_x - (max_x - min_x) * 0.05
    max_x = max_x + (max_x - min_x) * 0.05
    min_y = min_y - (max_y - min_y) * 0.05
    max_y = max_y + (max_y - min_y) * 0.05
    x_vals = np.linspace(min_x, max_x, 100)
    y_vals = np.linspace(min_y, max_y, 100)
    XX, YY = np.meshgrid(x_vals, y_vals)
    grid_r, grid_c = XX.shape
    ZZ = np.zeros((grid_r, grid_c))
    for i in range(grid_r):
        for j in range(grid_c):
            ZZ[i, j] = pred_fun(XX[i, j], YY[i, j])
    pl.contourf(XX, YY, ZZ, 100, cmap = pl.cm.coolwarm, vmin= -1, vmax=2)
    pl.colorbar()
    pl.xlabel("x")
    pl.ylabel("y")

def gen_pred_fun(clf):
    def pred_fun(x1, x2):
        x = np.array([[x1, x2]])
        return clf.predict(x)[0]
    return pred_fun

"""## Neurona artificial

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/6/60/ArtificialNeuronModel_english.png/600px-ArtificialNeuronModel_english.png" >

* El perceptrón es un algoritmo de clasificación que genera una predicción para una entrada $(x)$ de la siguiente manera:
$$\textrm{Predicción}(x)=\begin{cases}
C_{1} & \mbox{si }f(x)\ge \theta\\
C_{2} & \mbox{si }f(x)<\theta
\end{cases}$$

* De igual forma, $f(x)$ está definida como una suma ponderada sobre los elementos de la entrada:
$$
f(x) =  \sum_{i=1}^{n} {w_i x_i}
$$
dónde $x$ corresponde a la entrada, $w$ corresponde a los pesos que se multiplican por la entrada $x$ y $w_0$ al sesgo.

* Para poder generar $\textrm{Predicción}(x)$, se toma la salida de $f(x)$ y se le aplica una **función de activación** $\varphi$. Así la salida del perceptrón es de la siguiente forma:
$$
y = \varphi( \sum_{i=1}^{n} {w_i x_i})
$$

* Es común encontrar en la literatura que se mencione que una neurona se activó, si su valor de la salida $y$ superó el umbral $\theta$ definido para la neurona.

**¿Cómo escoger $\varphi$?**

## Función de activación de paso

El caso más sencillo se conoce como la función de activación de paso. La función de activación de paso se define de la siguiente manera:

$$\phi(x)=\begin{cases}
1 & \mbox{si }x\ge \theta\\
0 & \mbox{si }x<\theta
\end{cases}$$
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the step function
def step_function(x, theta=2):
  return np.where(x >= theta, 1, 0)

# Generate x values
x = np.linspace(-5, 5, 100)

# Calculate y values using the step function
y = step_function(x)

# Plot the step function
plt.plot(x, y, 'r-*')
plt.xlabel("x")
plt.ylabel("Activation")
plt.title("Step Activation Function")
plt.grid(True)
plt.show()

"""## Función de activación logística

La función de activación logística está basada en la función sigmoide $\sigma$. La función sigmoíde para cualquier valor $z$ se define de la siguiente manera:

$$\sigma(z) = \frac{1}{1 - e^{-z}}$$

Cómo se puede observar en la imagen, la función sigmoide genera valores entre $0$ y $1$. A diferencia de la función de activación de paso, la sigmoide genera una transición entre $0$ y $1$. La salida del perceptrón queda definida de la siguiente manera:

$$
y = \sigma(\theta + \sum_{i=1}^{n} {w_i x_i})
$$
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(z):
  return 1 / (1 + np.exp(-z))

# Generate x values
x = np.linspace(-6, 6, 100)

# Calculate y values using the sigmoid function
y = sigmoid(x)

# Plot the sigmoid function
plt.plot(x, y,'r-+')
plt.xlabel("x")
plt.ylabel("Activation")
plt.title("Sigmoid Activation Function")
plt.grid(True)
plt.show()

def sigmoid(z):
  return 1 / (1 + np.exp(-z))

def step_function(x, theta=3):
  return np.where(x >= theta, 1, 0)


# Generate x values
x = np.linspace(-6, 6, 100)

# Calculate y values using the sigmoid function
y = sigmoid(x)
z = step_function(x)

# Plot the sigmoid function
plt.plot(x, y,'r-+', label='Sigmoide')
plt.plot(x, z,'b-*', label='Paso')
plt.xlabel("x")
plt.ylabel("Activation")
plt.title("Comparación")
plt.grid(True)
plt.legend()
plt.show()

"""## Implementación del perceptrón en Scikit-Learn

Un perceptron es una red neuronal sin capas intermedias, es decir solo un capa de salida, las neuronas en la capa de salida usan la función de activación de paso. Usando `sklearn.linear_model.Perceptron` podemos encontrar la implementación del perceptrón. El entrenamiento del modelo se hace usando gradiente descendente.

### ¿Cómo programar una neurona para calcular la función `AND`?

| $$X$$ | $$ Y $$ | $$ X\&Y $$ |
| - | - | - |
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 1 |

### AND Neural Network
![texto del vínculo](https://drive.google.com/uc?id=19n3aQ07U7qFJfvl6PjLkbLZb9M7ZmCCP)

Para *programar* manualmente el perceptron, vamos a fijar sus parámetros con las siguientes instrucciones:
"""

from sklearn.linear_model import Perceptron
clf = Perceptron()
clf.coef_ = np.array([[0.7, -0.3]])
clf.intercept_ = np.array([1])
clf.classes_ = np.array([0, 1])

"""Ahora vamos a aplicarla a datos de entrada:"""

X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = [0, 0, 0, 1]

print('Predicciones: {}'.format(clf.predict(X)))
print('Accuracy: {}'.format(clf.score(X, y)))

"""Puesto que los pesos y umbral fueron arbitrariamente fijados, las predicciones no son las esperadas. ¿Qué pesos y umbral debemos poner para que funcione como una compuerta AND?

Generalmente las redes neuronales no se programan manualmente, sino que se aplicar un algoritmo de aprendizaje o entrenamiento. Esto se lleva a cabo en con la función `fit()`. Esta función recibe un arreglo de tamaño `[n_muestras, n_características]`. `n_características` define el número de conexiones de entrada del perceptrón. A la salida del perceptrón, se le aplica la función de activación de paso.

`Perceptron` nos permite obtener los valores de los pesos $w_1$ y $w_2$, y el sesgo $w_0$
"""

clf.fit(X, y)

print('w_1 y w_2: {}'.format(clf.coef_))
print('w_0: {}'.format(clf.intercept_))

"""Revisamos las predicciones para nuestro conjunto de datos:"""

print('Predicciones: {}'.format(clf.predict(X)))
print('Accuracy: {}'.format(clf.score(X, y)))

"""Visualizamos la región de decisión."""

pl.figure(figsize = (10, 6))
plot_decision_region(X, gen_pred_fun(clf))
plot_data(X, y, size=100)

"""### ¿Cómo programar una neurona para calcular la función XOR?

| $$X$$ | $$ Y $$ | $$ X\oplus Y $$ |
| - | - | - |
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |
"""

X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = [0, 1, 1, 0]

pl.figure(figsize = (10, 6))
plot_data(X, y, size=100)
plt.show()

clf = Perceptron()
clf.fit(X, y)

"""Observamos las predicciones y la superficie de decisión:"""

print('Valor original: {}'.format(y))
print('Valor predicho: {}'.format(clf.predict(X)))
print('Accuracy: {}'.format(clf.score(X, y)))

pl.figure(figsize = (10, 6))
plot_decision_region(X, gen_pred_fun(clf))
plot_data(X, y, size=100)

"""**Problemas**
* Es imposible encontrar un modelo lineal que separe los puntos de ambas clases en el problema `XOR`. Una solución es usar dos neuronas.

# Perceptron multicapa
El perceptron multicapa (Multilayer Perceptron, MLP en inglés) es un tipo especial de red neuronal en el cual se apilan varias capas de perceptrones. En inglés tambien se le denomina como **Feedforward neural network**. El perceptrón multicapa está motivado por la poca capacidad del perceptrón sencillo de modelar funciones no lineales. En un MLP agrupamos tantas capas como necesitemos. A continuación, presentamos una red multicapa que cuenta con:

* Capa de entrada: Recibe los datos de entrada.
* Capa oculta: Cuenta con uno o más neuronas.
* Capa de activación: Aplica una función de activación sobre la salida de cada neurona de la capa oculta.
* Cada de salida: Produce la predicción para completar la tarea supervisada. Puede ser de clasificación o *regresión*.

![texto del vínculo](https://drive.google.com/uc?id=1Rj7fVeqHdW3fI4EReGMbdxAwD4_5gIVM)

## ¿Cómo resolver el problema de la función XOR?

Scikit-Learn nos permite trabajar con redes multicapa usando `sklearn.neural_network.MLPClassifier`. Una red multicapa se puede entrenar usando **gradiente descendente**, por lo tanto se pueden usanr métodos como **gradiente descendente estocástico** u otros métodos de optimización. El valor del gradiente determina qué tanto debo modificar los pesos de mi red (parámetros entrenables) para resolver la tarea de predicción.

A continuación vamos a definir la siguiente arquitectura para resolver el problema de la función XOR.

`MLPClassifier` permite definir esta arquitectura de la siguiente manera:

* **Capa de entrada**: El tamaño de la capa de entrada es definido cuando se llama a la función `fit()`. El tamaño está definido por el número de características (o columnas) de la matriz de características `X`.
* **Capa(s) ocultas**: El número de capas ocultas y el tamaño de cada una es definido por el parámetro `hidden_layer_size` de la clase `MLPClassifier`. Este parámetro consiste en una tupla de $n$ elementos, donde $n$ es igual al número de capas ocultas. Cada elemento de la tupla determina el número de neuronas de esa capa oculta.
* **Función de activación**: Esta función se define usando el parámetro `activation` de `MLPClassifier`. Este parámetro puede ser `logistic`, `relu`, `tanh` o `identity`.
* **Capa de salida**: Se define cuando se llama a la función `fit()`. La capa de salida contiene una única neurona, cuya función de activación se define con base al tipo de tarea de clasificación. Si es una tarea de clasificación binaria usa una función de activación logística. Si la tarea es multiclase se usa una función de activación SoftMax.

Adicionalmente `MLPClassifier` recibe los siguientes parámetros:

* `solver`: Puede ser '*lbfgs*', '*sgd*' o '*adam*'. '*lbfgs*' es una técnica de optimización muy útil para conjuntos pequeños. Mientras que '*sgd*' y '*adam*' usan gradiente descendente estocástico y son apropiados para conjunto de datos grandes.
* `alpha`: $\alpha$ controla el parámetro de regularización. $\alpha$ permite penalizar aquellos pesos $w$ grandes.
"""

from sklearn.neural_network import MLPClassifier

X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = [0, 1, 1, 0]

clf = MLPClassifier(solver='lbfgs', alpha=1e-5, activation='logistic',
                    hidden_layer_sizes=2, random_state = 3)
clf.fit(X, y)

"""Evaluamos el desempeño del clasificador sobre el conjunto de datos:"""

clf.score(X, y)

"""Visualizamos la superficie de decisión:"""

pl.figure(figsize = (10, 6))
plot_decision_region(X, gen_pred_fun(clf))
plot_data(X, y, size=100)

"""`MLPClassifier` también nos permite acceder a la matriz de parámetros $w$ y a los sesgos $w_0$. `coefs_` nos regresa una lista que corresponde a los parámetros aprendidos. A continuación verificamos el tamaño de cada matriz y su respectivo valor."""

print([a.shape for a in clf.coefs_])
print(clf.coefs_)

"""Para acceder a los sesgos, se puede usar `.intercepts_`"""

print([a.shape for a in clf.intercepts_])
print(clf.intercepts_)

"""### **Ventajas**

* A través de las capas ocultas, se pueden modelar relaciones de alto nivel entre las entradas. Por ejemplo, en el dominio de reconocimiento de objetos en imágenes, se puede aprender que el conjunto de dos ojos, una nariz y una boca forman una imagen.
* Las funciones de activación al ser no lineales, le permiten al modelo aprender funciones de separación más elaboradas.

### **Desventajas**
* La complejidad del modelo puede aumentar rápidamiente con respecto al número de capas y de neuronas por capa. Contemple el caso de una red con las siguientes características:

    * 1 capa de entrada de tamaño 50.
    * 1 capa oculta de 256 neuronas.
    * 1 capa oculta de 512 neuronas.
    * 1 capa de clasificación binaria.

* Bajo esta configuración tenemos que el número de parámetros está distribuido de la siguiente manera:
    * Conexiones entre la capa de entrada y la primera capa oculta: $256*50 + 256 = 13056. Donde la segunda parte corresponde a los sesgos.
    * Conexiones entre la primera capa oculta y la segunda capa oculta: 256*512 + 512 = 131584.
    * Conexiones entre la segunda capa oculta y la capa de clasificación: 512 + 1 = 513.
    * Para un total de *145153* parámetros entrenables.

### Recomendaciones prácticas:
* Hacer un escalamiento de los datos de entrada. `MLPClassifier` es muy sensible a la escala de los datos de entrada.
* Explorar el número de neuronas por capa y el parámetro $\alpha$ usando `GridSearchCV`.
* Usar '*lbfgs*' como `solver` para conjuntos de datos pequeños. Mientras que '*adam*' es más recomendado para conjuntos de datos grandes.

## Little Red Riding Hood (Caperucita Roja)

`MLPClassifier` también puede manejar problemas de tipo multi-etiqueta. Considere el problema de caperucita roja, en el cual caperucita debe decidir qué acción llevar a cabo con base a la apariencia de la abuelita.

Generemos el conjunto de datos:
"""

from sklearn.neural_network import MLPClassifier
X = np.array([[1,1,0,0], [0,1,1,0], [0,0,0,1]])
y = np.array([[1,0,0,0], [0,0,1,1], [0,1,1,0]])
df = pd.DataFrame(X, columns=['Big Ears', 'Big Teeth', 'Handsome', 'Wrinkled'])
print(df.join(pd.DataFrame(y, columns=['Scream', 'Hug', 'Food', 'Kiss'])))

"""Usamos los siguientes parámetros:
* `solver`: *adam*
* `max_iter`: *5000*

Definimos una red multicapa con una capa oculta de tamaño $3$.
"""

clf = MLPClassifier(solver='adam', alpha=1e-5, activation='logistic', max_iter=5000,
                    hidden_layer_sizes=(3), random_state=1)
clf.fit(X, y)

"""Scikit-Learn nos permite consultar las probabilidades para cada etiqueta así:"""

y_prob = clf.predict_proba(X)
df = pd.DataFrame(X, columns=['Big Ears', 'Big Teeth', 'Handsome', 'Wrinkled'])
print(df.join(pd.DataFrame(y_prob, columns=['Scream', 'Hug', 'Food', 'Kiss'])))

"""Al momento de hacer las predicciones, `MLPClassifier` toma aquellas probabilidades mayores a $0.5$ y les asigna la etiqueta $1$, mientras que aquellos valores menores a $0.5$ le son asignados la etiqueta $0$."""

y_pred = clf.predict(X)
df = pd.DataFrame(X, columns=['Big Ears', 'Big Teeth', 'Handsome', 'Wrinkled'])
print(df.join(pd.DataFrame(y_pred, columns=['Scream', 'Hug', 'Food', 'Kiss'])))

clf.score(X, y)

"""Visualizamos la curva de pérdida a lo largo de cada ejemplo proporcionado al modelo."""

plt.ylabel('Mean Square Error')
plt.xlabel('Epochs')
plt.plot(clf.loss_curve_)
plt.grid()
plt.show()

"""Ahora hagamos una predicción con un ejemplo no visto por la red neuronal durante el entrenamiento:"""

X1 = np.array([[1,1,0,0]])
y_prob = clf.predict_proba(X1)
df = pd.DataFrame(X1, columns=['Big Ears', 'Big Teeth', 'Handsome', 'Wrinkled'])
df.join(pd.DataFrame(y_prob, columns=['Scream', 'Hug', 'Food', 'Kiss']))



"""$\theta +5$

$\frac{1}{1+\theta +3}$
"""